{
    getPortfoliosByIds(ids: ${ID}) {
        access
        awardCount
        awards {
            count
            level
            levelLabel
        }
        campaigns {
            assets {
                fullUrl
                id
                label
                thumbnailUrl
                type
            }
            awardCount
            awards {
                count
                level
                levelLabel
            }
            brand {
                name
                slug
            }
            caseStudy {
                background
                description
                execution
                idea
                outcome
                strategy
            }
            company {
                name
                town
            }
            credits {
                companies {
                    location
                    name
                    role
                    slug
                }
                people {
                    company
                    name
                    role
                    slug
                }
            }
            downloadable
            entryTypes {
                entries {
                    category
                    level
                    levelLabel
                    section
                    slug
                }
                name
                slug
            }
            festival {
                code
                name
            }
            id
            requiredUserActions
            saveable
            shortlisted
            slug
            tags
            title
            year
        }
        city
        company
        country
        directoryListing
        experience
        fullname
        id
        imageUrl
        interests
        jobtitle
        public
        region
        role
        skills
        slug
    }
}